// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: users.sql

package database

import (
	"context"

	"github.com/google/uuid"
)

const createUser = `-- name: CreateUser :one
INSERT INTO users (username, email,api_key) VALUES ($1, $2, 
encode(sha256(random()::text::bytea), 'hex')) RETURNING id, username, email, created_at, updated_at, api_key
`

type CreateUserParams struct {
	Username string
	Email    string
}

func (q *Queries) CreateUser(ctx context.Context, arg CreateUserParams) (User, error) {
	row := q.db.QueryRowContext(ctx, createUser, arg.Username, arg.Email)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.Email,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.ApiKey,
	)
	return i, err
}

const userByApiKey = `-- name: UserByApiKey :one
SELECT id, username, email, created_at, updated_at, api_key FROM users WHERE api_key = $1
`

func (q *Queries) UserByApiKey(ctx context.Context, apiKey string) (User, error) {
	row := q.db.QueryRowContext(ctx, userByApiKey, apiKey)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.Email,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.ApiKey,
	)
	return i, err
}

const userByEmail = `-- name: UserByEmail :one
SELECT id FROM users WHERE email = $1
`

func (q *Queries) UserByEmail(ctx context.Context, email string) (uuid.UUID, error) {
	row := q.db.QueryRowContext(ctx, userByEmail, email)
	var id uuid.UUID
	err := row.Scan(&id)
	return id, err
}
